sudo: false
language: node_js
node_js :
  - "4.5.0"
addons:
  apt:
    packages:
      - libssl-dev
cache:
  directories:
  - /tmp/htslib
  - /tmp/samtools
  - /tmp/freebayes
env:
  global:
    - MONGODB_VERSION=3.2.4
    - FREEBAYES_VERSION="v1.1.0"
    - BIOBAMBAM_VERSION="2.0.50-release-20160705161609"
    - HTSLIB_VERSION="1.3.2"
    - SAMTOOLS1_VERSION="1.3.1-npg-Sep2016"
before_install:
  - ./.travis/install.sh
  - export PATH="/tmp/usr/bin:${PATH}"
  - npm install -g npm@3.10.7
  - npm --version
  - npm install -g grunt-cli
script:
  - grunt -v
