---
- name: download htslib
  git:
    repo: https://github.com/wtsi-npg/htslib.git
    version: "{{ htslib_version }}"
    dest: "{{ user_home.stdout }}/htslib"
    update: no
  register: new_htslib_repo
- name: htslib autoreconf
  command: /usr/bin/autoreconf
  args:
    chdir: "{{ user_home.stdout }}/htslib"
  when: new_htslib_repo|changed
- name: htslib configure
  command: "{{ user_home.stdout }}/htslib/configure --enable-plugins"
  args:
    chdir: "{{ user_home.stdout }}/htslib"
  when: new_htslib_repo|changed
- name: htslib make
  make:
    chdir: "{{ user_home.stdout }}/htslib"
  when: new_htslib_repo|changed
...
